
### Create a new user
POST http://localhost:3005/reports
Content-Type:  application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 10000,
    "lng": 0,
    "lat": 0,
    "price": 500000
}

### Approve an exiting report
PATCH http://localhost:3005/reports/8
Content-Type:  application/json

{
    "approved": false
}


### Get an estimate for an existing vehicle
Get http://localhost:3005/reports?make=toyota&model=colla&lng=0&lat=0&year=1980&mileage=100
